vaadin-miki/super-fields

demo-v14/pom.xml
superfields/pom.xml

with exception of date-time-picker-flow, which will be transitive until it is included in Vaadin 14.X release
closes #76

dependencies are no longer transitive

---

superfields/src/main/java/org/vaadin/miki/superfields/lazyload/ComponentObserver.java
superfields/src/main/java/org/vaadin/miki/superfields/lazyload/ObservedField.java
superfields/src/main/resources/META-INF/resources/frontend/component-observer.js

Also minor fixes to support that behaviour also in `ComponentObserver`.
closes #93

ObservedField now works when removed and added again

---

superfields/src/main/java/org/vaadin/miki/superfields/dates/DatePatternHelper.java
superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDatePicker.java
superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDateTimePicker.java

turned `DatePatternHelper` into a proper helper object and delegated a few calls there, just to have the code in one place for both `SuperDatePicker` and `SuperDateTimePicker`
demo app shows that this approach works
closes #105

#105 fixed

---

.github/workflows/setversion.yml
superfields/release-notes.md

closes #107 
workflows were updated to fetch closed tickets from a milestone that matches release branch name (so for branch `release-0.6.1` milestone starting with `0.6.1 ` will be matched

automated release notes

---

.github/workflows/makerelease.yml

closes #117 
when a new push to `master` is done, the workflow should fetch the latest version from `superfields/release-notes.md` and then determine the following:
* number of the latest version
* title of the release
* contents of the release

117 auto release

---

.github/workflows/codequality.yml
demo-v14/frontend/styles/super-number-fields-styles.css
demo-v14/src/main/java/org/vaadin/miki/MainView.java
superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java

default class name for the TextField inside number fields
also, when setting id of number fields the TextField inside will have its id changed to `belongs-to-whatever-id-was-set-to-number-field`
closes #126 
closes #127

#126 and #127 done

---

demo-v14/src/main/java/org/vaadin/miki/MainView.java
superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDatePicker.java
superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDateTimePicker.java
superfields/src/main/java/org/vaadin/miki/superfields/text/CanReceiveSelectionEventsFromClient.java
superfields/src/main/java/org/vaadin/miki/superfields/text/CanSelectText.java
superfields/src/main/java/org/vaadin/miki/superfields/text/SuperTextArea.java
superfields/src/main/java/org/vaadin/miki/superfields/text/SuperTextField.java
superfields/src/main/java/org/vaadin/miki/superfields/text/TextSelectionDelegate.java
superfields/src/main/java/org/vaadin/miki/superfields/text/TextSelectionEvent.java
superfields/src/main/java/org/vaadin/miki/superfields/text/TextSelectionListener.java
superfields/src/main/java/org/vaadin/miki/superfields/text/TextSelectionNotifier.java
superfields/src/main/java/org/vaadin/miki/superfields/text/WithReceivingSelectionEventsFromClientMixin.java
superfields/src/main/resources/META-INF/resources/frontend/super-text-area.js
superfields/src/main/resources/META-INF/resources/frontend/super-text-field.js
superfields/src/main/resources/META-INF/resources/frontend/text-selection-mixin.js
superfields/src/test/java/org/vaadin/miki/superfields/text/AbstractTestForTextSelection.java
superfields/src/test/java/org/vaadin/miki/superfields/text/SuperTextAreaTest.java
superfields/src/test/java/org/vaadin/miki/superfields/text/SuperTextFieldTest.java

closes #122 
introduces `SuperTextField` and `SuperTextArea` together with `CanSelectText` and `CanReceiveSelectionEventsFromClient` (somewhat lengthy name, but could not figure out anything more descriptive)

122 super text field

---

demo-v14/frontend/styles/demo-styles.css
demo-v14/frontend/styles/super-tabs-styles.css
demo-v14/src/main/java/org/vaadin/miki/MainView.java
superfields/src/main/java/org/vaadin/miki/superfields/tabs/SuperTabs.java
superfields/src/main/java/org/vaadin/miki/superfields/tabs/TabContentGenerator.java
superfields/src/main/java/org/vaadin/miki/superfields/tabs/TabHandler.java
superfields/src/main/java/org/vaadin/miki/superfields/tabs/TabHeaderGenerator.java
superfields/src/main/resources/META-INF/resources/frontend/styles/super-tabs-multiline.css

also cleaned up some sonar warnings
closes #146 
closes #135 
`SuperTabs.isMultiline()` controls multilineness, which is by default turned off

#135 and #146 done

---

demo-v14/src/main/java/org/vaadin/miki/MainView.java
superfields/src/main/java/org/vaadin/miki/superfields/unload/UnloadObserver.java

using ComponentUtil.getData/setData to keep the instance associated with a given UI
creating UnloadObserver does not add it anywhere, that still needs to be done manually
also updated demo app to reflect changes
closes #178

#178 UnloadObserver is now UI-scoped singleton

---

superfields/README.md
superfields/src/main/java/org/vaadin/miki/superfields/unload/UnloadObserver.java
superfields/src/test/java/org/vaadin/miki/superfields/unload/SampleView.java
superfields/src/test/java/org/vaadin/miki/superfields/unload/UnloadObserverTest.java

`UnloadObserver` now has two static methods for creating/reusing an instance attached to a given component/current UI, named `getAttached`.
closes #182 
closes #183

182 183 unload observer fixes

---

superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
superfields/src/test/java/org/vaadin/miki/superfields/numbers/BaseTestsForIntegerNumbers.java

#199 fixed

---

superfields/src/main/java/org/vaadin/miki/superfields/unload/UnloadObserver.java

This enables a View setup where the UnloadObserver is added to a child view "A". Once the user navigates to another child view "B" of the same MainView, the UnloadObserver must be gone. I could do this manually in child view "A" (and all other views with that behaviour) or the UnloadObserver could take care of this directly so I don't have to remember to add a detach listener to all my views that use an unloadObserver. I believe this does not break the component for those that attach the UnloadObserver to the UI directly.

Removing beforeunload EventListener on detach

---

demo-v14/src/main/java/org/vaadin/miki/DemoComponentFactory.java
superfields/src/main/java/org/vaadin/miki/shared/dates/DatePattern.java
superfields/src/main/java/org/vaadin/miki/shared/dates/DatePatterns.java
superfields/src/main/java/org/vaadin/miki/superfields/dates/DatePatternDelegate.java
superfields/src/main/resources/META-INF/resources/frontend/date-pattern-mixin.js

closes #212 
closes #216 
check for invoking extra filling of the short year is done now based on length of the pattern rather than presence of the short year indicator

super date (time) picker now optionally always accepts short year

---

README.md
demo-v14/src/main/java/org/vaadin/miki/DemoComponentFactory.java
superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperIntegerField.java
superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperLongField.java
superfields/src/test/java/org/vaadin/miki/superfields/numbers/BaseTestsForIntegerNumbers.java

Calling `setLocale` now preserves the information about the precision of the number (max/min allowed digits).
closes #224

Number fields preserve precision info between locale changes

---

.github/workflows/releasenotes.yml
.github/workflows/setversion.yml

closes #220 
setting version now also updates the dependency in the demo (which was why the process failed in the first place)

220 release process

---

demo-v14/src/main/java/org/vaadin/miki/demo/builders/CanModifyTextBuilder.java
superfields/README.md
superfields/src/main/java/org/vaadin/miki/markers/CanModifyText.java
superfields/src/main/java/org/vaadin/miki/shared/text/TextModificationDelegate.java
superfields/src/main/java/org/vaadin/miki/shared/text/TextSelectionDelegate.java
superfields/src/main/java/org/vaadin/miki/superfields/text/SuperTextArea.java
superfields/src/main/java/org/vaadin/miki/superfields/text/SuperTextField.java
superfields/src/main/resources/META-INF/resources/frontend/text-selection-mixin.js

closes #290 
`text-selection-mixin` now has a `replaceText()` method that can be called from `TextModificationDelegate`, which in turn is an extension of `TextSelectionDelegate` that is available for `SuperTextField` and `SuperTextArea`, but not for date field nor number fields (the code can still be triggered from client side, but it is not exposed on the java side)

290 insert text at caret

---

demo-v14/src/main/java/org/vaadin/miki/demo/builders/FocusNotifierBuilder.java
superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java

`.focus()` and `.blur()` are now forwarded to the underlying text field (in number fields)

#329 fixed

---

superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperBigDecimalField.java
superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperBigDecimalFieldTest.java

#358 hopefully fixed

---

demo-v23/src/main/java/org/vaadin/miki/demo/builders/ObjectFieldBuilder.java
demo-v23/src/main/java/org/vaadin/miki/demo/data/Book.java
demo-v23/src/main/java/org/vaadin/miki/demo/data/Format.java
superfields/src/main/java/org/vaadin/miki/superfields/util/factory/MetadataProperties.java
superfields/src/main/java/org/vaadin/miki/superfields/util/factory/ObjectFieldFactory.java
superfields/src/test/java/org/vaadin/miki/superfields/object/EnumObject.java
superfields/src/test/java/org/vaadin/miki/superfields/object/EnumObjectTest.java
superfields/src/test/java/org/vaadin/miki/superfields/object/TestingMode.java

`ObjectFieldFactory` now supports enums.
closes #400 
closes #406

#400 #406 done

---

demo-v24/src/main/java/org/vaadin/miki/DemoComponentFactory.java
demo-v24/src/main/java/org/vaadin/miki/demo/builders/HasTextInputModeBuilder.java
superfields/src/main/java/org/vaadin/miki/markers/HasTextInputMode.java
superfields/src/main/java/org/vaadin/miki/markers/WithTextInputModeMixin.java
superfields/src/main/java/org/vaadin/miki/shared/text/TextInputMode.java
superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperBigDecimalField.java
superfields/src/main/java/org/vaadin/miki/superfields/text/SuperTextField.java

471 numberfield keyboard prompt

---

demo-v24/src/main/java/org/vaadin/miki/demo/builders/AbstractSuperFloatingPointFieldBuilder.java
demo-v24/src/main/java/org/vaadin/miki/demo/builders/AbstractSuperNumberFieldBuilder.java
superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperFloatingPointField.java
superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperBigDecimalField.java
superfields/src/main/java/org/vaadin/miki/util/RegexTools.java
superfields/src/main/java/org/vaadin/miki/util/StringTools.java
superfields/src/test/java/org/vaadin/miki/superfields/numbers/BaseTestsForFloatingPointNumbers.java
superfields/src/test/java/org/vaadin/miki/superfields/numbers/BaseTestsForIntegerNumbers.java
superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperBigDecimalFieldTest.java
superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperDoubleFieldTest.java
superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperIntegerFieldTest.java
superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperLongFieldTest.java
superfields/src/test/java/org/vaadin/miki/util/RegexToolsTest.java
superfields/src/test/java/org/vaadin/miki/util/StringToolsTest.java

#472 number fields have now configurable alternative symbols

---

demo-v24/src/main/java/org/vaadin/miki/demo/builders/WithNullValueOptionallyAllowedBuilder.java
demo-v24/src/main/java/org/vaadin/miki/demo/providers/ComponentSelectProvider.java
demo-v24/src/main/resources/ComponentSelect.md
superfields/README.md
superfields/src/main/java/org/vaadin/miki/markers/WithClearButtonMixin.java
superfields/src/main/java/org/vaadin/miki/markers/WithNullValueOptionallyAllowedMixin.java
superfields/src/main/java/org/vaadin/miki/markers/WithReceivingSelectionEventsFromClientMixin.java
superfields/src/main/java/org/vaadin/miki/superfields/buttons/ButtonSelect.java
superfields/src/main/java/org/vaadin/miki/superfields/componentselect/ComponentSelect.java
superfields/src/main/java/org/vaadin/miki/superfields/componentselect/ComponentSelectHelpers.java
superfields/src/test/java/org/vaadin/miki/superfields/componentselect/ComponentSelectTest.java

#488 #494 done

---

pom.xml
superfields/pom.xml
superfields/src/main/java/org/vaadin/miki/superfields/text/SuperTextArea.java
superfields/src/main/java/org/vaadin/miki/superfields/text/SuperTextField.java
superfields/src/main/resources/META-INF/resources/frontend/text-selection-mixin.js
superfields/src/test/java/org/vaadin/miki/superfields/dates/DatePatternDelegateTest.java

#513 #514 done
