- demo-v14/src/main/java/org/vaadin/miki/MainView.java
- superfields/README.md
- superfields/src/main/java/org/vaadin/miki/superfields/SuperIntegerField.java
- superfields/src/main/java/org/vaadin/miki/superfields/SuperLongField.java
- superfields/src/test/java/org/vaadin/miki/superfields/SuperIntegerFieldTest.java
- superfields/src/test/java/org/vaadin/miki/superfields/SuperLongFieldTest.java
tests, docs and demo updated
closes #4
> #4 likely done

- .github/settings.xml
- .github/workflows/mavenpublish.yml
- demo-v14/pom.xml
- demo-v14/src/main/java/org/vaadin/miki/MainView.java
- pom.xml
- superfields/pom.xml
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperFloatingPointField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperBigDecimalField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperDoubleField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperIntegerField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperLongField.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/BaseTestsForFloatingPointNumbers.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/BaseTestsForIntegerNumbers.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperBigDecimalFieldTest.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperDoubleFieldTest.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperIntegerFieldTest.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperLongFieldTest.java
closes #14 - hopefully, will surely require some fine-tuning after the fact
> 14 make release

- .github/workflows/mavenpublish.yml
attempt 2 to have automated releases
> #16 specifying superfields in workflow

- demo-v14/src/main/java/org/vaadin/miki/MainView.java
- superfields/README.md
- superfields/src/main/java/org/vaadin/miki/markers/HasLocale.java
- superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDatePicker.java
- superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDatePickerI18n.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
- superfields/src/main/resources/superdatepickeri18n_en.properties
- superfields/src/main/resources/superdatepickeri18n_fi.properties
- superfields/src/main/resources/superdatepickeri18n_pl.properties
- superfields/src/test/java/org/vaadin/miki/superfields/dates/SuperDatePickerI18nTest.java
> #12 SuperDatePicker ready

- demo-v14/package-lock.json
- demo-v14/package.json
- demo-v14/src/main/java/org/vaadin/miki/MainView.java
- superfields/pom.xml
- superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDatePicker.java
- superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDatePickerI18n.java
- superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDatePickerI18nHelper.java
- superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDateTimePicker.java
the locale changes at runtime is broken, but that seems to be a Vaadin issue
closes #20
> #20 most likely done

- .github/workflows/deployheroku.yml
- README.md
- demo-v14/README.md
- demo-v14/pom.xml
the app is now deployed to Heroku at https://superfields.herokuapp.com/ on each release
closes #37
> 37 demo publish to heroku

- demo-v14/pom.xml
- pom.xml
- superfields/pom.xml
> #35 version set to 0.3.0

- demo-v14/frontend/styles/demo-styles.css
- demo-v14/src/main/java/org/vaadin/miki/MainView.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/CellGenerator.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/CellInformation.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/CellSelectionEvent.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/CellSelectionHandler.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/ItemGrid.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/RowComponentGenerator.java
- superfields/src/test/java/org/vaadin/miki/superfields/itemgrid/ItemGridTest.java
> 34 itemgrid

- demo-v14/pom.xml
- pom.xml
- superfields/README.md
- superfields/assembly/MANIFEST.MF
- superfields/assembly/assembly.xml
- superfields/pom.xml
Updates to pom, plus some extra files for Directory release.
> Vaadin Directory and version 0.4.0

- demo-v14/frontend/styles/demo-styles.css
- demo-v14/src/main/java/org/vaadin/miki/MainView.java
- superfields/README.md
- superfields/src/main/java/org/vaadin/miki/markers/WithIdMixin.java
- superfields/src/main/java/org/vaadin/miki/superfields/lazyload/LazyLoad.java
closes #50 and introduces new component, `LazyLoad`
> 50 lazyload 

- demo-v14/package-lock.json
- demo-v14/package.json
- pom.xml
- superfields/src/main/resources/superdatepickeri18n_de.properties
- superfields/src/main/resources/superdatepickeri18n_it.properties
also #54 for German and Italian
closes #52
> #52 source level now Java 8

- demo-v14/pom.xml
- pom.xml
- superfields/README.md
- superfields/pom.xml
also README.md updated in superfields
> #60 version bumped

- demo-v14/src/main/java/org/vaadin/miki/MainView.java
- superfields/README.md
- superfields/src/main/java/org/vaadin/miki/superfields/lazyload/IntersectionObserverComponent.java
- superfields/src/main/java/org/vaadin/miki/superfields/lazyload/LazyLoad.java
- superfields/src/main/java/org/vaadin/miki/superfields/lazyload/ObservedField.java
closes #66 
new `ObservedField` component, updated demo and readme
> ObservedField with value corresponding to the current on-screen status

- demo-v14/pom.xml
- pom.xml
- superfields/pom.xml
> 70 fixed maven issues

- demo-v14/src/main/java/org/vaadin/miki/MainView.java
- superfields/README.md
- superfields/src/main/java/org/vaadin/miki/superfields/unload/UnloadEvent.java
- superfields/src/main/java/org/vaadin/miki/superfields/unload/UnloadListener.java
- superfields/src/main/java/org/vaadin/miki/superfields/unload/UnloadObserver.java
- superfields/src/main/resources/META-INF/resources/frontend/unload-observer.js
> UnloadObserver and related code

- demo-v14/frontend/styles/demo-styles.css
- demo-v14/src/main/java/org/vaadin/miki/MainView.java
- superfields/src/main/java/org/vaadin/miki/markers/WithIdMixin.java
- superfields/src/main/java/org/vaadin/miki/markers/WithItemsMixin.java
- superfields/src/main/java/org/vaadin/miki/superfields/tabs/LambdaTabHandler.java
- superfields/src/main/java/org/vaadin/miki/superfields/tabs/SuperTabs.java
- superfields/src/main/java/org/vaadin/miki/superfields/tabs/TabHandler.java
- superfields/src/main/java/org/vaadin/miki/superfields/tabs/TabHandlers.java
- superfields/src/test/java/org/vaadin/miki/superfields/tabs/SuperTabsTest.java
closes #80 
closes #82 
closes #83 
Even more configuration for `SuperTabs`.
> SuperTabs improvements

- superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDatePicker.java
- superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDateTimePicker.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/ItemGrid.java
- superfields/src/main/java/org/vaadin/miki/superfields/lazyload/ComponentObserver.java
- superfields/src/main/java/org/vaadin/miki/superfields/lazyload/ObservedField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
- superfields/src/main/java/org/vaadin/miki/superfields/tabs/SuperTabs.java
- superfields/src/main/java/org/vaadin/miki/superfields/unload/UnloadObserver.java
closes #85 
closes #86 
closes #92
> Api improvements

- README.md
- demo-v14/pom.xml
- demo-v14/src/main/java/org/vaadin/miki/MainView.java
- pom.xml
- superfields/README.md
- superfields/pom.xml
> Release 0.6.0 ready

- demo-v14/pom.xml
> #98 fixed, hopefully

- .github/workflows/codequality.yml
- superfields/pom.xml
code quality will be triggered on each pull request to development and master
closes #108
> #108 set up in a separate profile

- .github/workflows/releasebranch.yml
- .github/workflows/setversion.yml
the code for closing milestone needs to be in `development` branch to be tested
closing a milestone should trigger pushing new branch, which in turn should result in updating version on that branch and making a PR to `master`
> #119 hopefully done, needs merging and testing

- demo-v14/src/main/java/org/vaadin/miki/InfoPage.java
- demo-v14/src/main/java/org/vaadin/miki/MainView.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/BaseTestsForIntegerNumbers.java
added unit tests and notifications in the demo app
closes #154
> #154 fixed

- .github/workflows/releasebranch.yml
- .github/workflows/releasenotes.yml
this hopefully will make #131 done
> #131 using separate step with PR for notes (with automatic merge)

- .github/workflows/releasebranch.yml
this should now merge the PR after a delay of 300 seconds, which should be more than enough for the actions to pass successfully
hopefully with this #131 can be closed
> #131 using delayed merge action

- superfields/release-notes.md
> Release notes for version 

- demo-v14/src/main/java/org/vaadin/miki/MainView.java
- superfields/src/main/java/org/vaadin/miki/superfields/unload/UnloadObserver.java
> 173 threadlocal unload observer

- .github/workflows/releasenotes.yml
- superfields/release-notes.md
now using proper links and explicitly removing all empty lines
closes #188
> #188 fixes to automated release-notes.md creation

- demo-v14/src/main/java/org/vaadin/miki/DemoComponentFactory.java
- demo-v14/src/main/java/org/vaadin/miki/DemoPage.java
- demo-v14/src/main/java/org/vaadin/miki/MainLayout.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperBigDecimalField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperDoubleField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperIntegerField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperLongField.java
new constructor for number fields that takes default value (as object) and label
closes #189 
closes #191
> #189 done, #191 fixed in the process

- .github/workflows/releasenotes.yml
> #188 fixed wrong path

- superfields/src/main/java/org/vaadin/miki/superfields/unload/UnloadObserver.java
> 206 client side listener bug

- README.md
> added contributors to README

- README.md
- demo-v14/src/main/java/org/vaadin/miki/DemoComponentFactory.java
- demo-v14/src/main/java/org/vaadin/miki/SuperFieldsGridItem.java
- superfields/src/main/java/org/vaadin/miki/superfields/gridselect/GridSelect.java
closes #211 
new component, `GridSelect`, which is a composition of `Grid` that `HasValue` and thus can be used as a single-selection field.
> GridSelect

- demo-v14/src/main/java/org/vaadin/miki/DemoComponentFactory.java
- demo-v14/src/main/java/org/vaadin/miki/DemoPage.java
closes #214 
`DemoPage` now caches pages generated so far instead of recreating every page on each request, and that seems to solve the problem
> #214 seems done

- demo-v14/src/main/java/org/vaadin/miki/DemoComponentFactory.java
- superfields/README.md
- superfields/src/main/java/org/vaadin/miki/superfields/gridselect/GridSelect.java
- superfields/src/main/java/org/vaadin/miki/superfields/gridselect/RestrictedModeGrid.java
- superfields/src/test/java/org/vaadin/miki/superfields/gridselect/GridSelectTest.java
> GridSelect's grid now can no longer have the selection mode changed

- demo-v14/pom.xml
- superfields/pom.xml
> #226 slf4j-simple is now demo dependency only

- superfields/release-notes.md
Reverts vaadin-miki/super-fields#233 because of #220
> Revert "Release notes for version "

- superfields/release-notes.md
Automatically updated notes 0.9.1.
> Release notes for version 0.9.1

- superfields/release-notes.md
Automatically updated notes 0.9.2.
> Release notes for version 0.9.2

- README.md
- demo-v14/src/main/java/org/vaadin/miki/demo/builders/WithMaximumSelectionSizeBuilder.java
- demo-v14/src/main/java/org/vaadin/miki/demo/providers/GridMultiSelectProvider.java
- demo-v14/src/main/java/org/vaadin/miki/demo/providers/GridSelectProvider.java
- demo-v14/src/main/java/org/vaadin/miki/demo/providers/SuperFieldsGridItem.java
- superfields/src/main/java/org/vaadin/miki/markers/HasMaximumSelectionSize.java
- superfields/src/main/java/org/vaadin/miki/markers/WithMaximumSelectionSize.java
- superfields/src/main/java/org/vaadin/miki/superfields/gridselect/AbstractGridSelect.java
- superfields/src/main/java/org/vaadin/miki/superfields/gridselect/GridMultiSelect.java
- superfields/src/main/java/org/vaadin/miki/superfields/gridselect/RestrictedModeGrid.java
- superfields/src/test/java/org/vaadin/miki/superfields/gridselect/GridMultiSelectTest.java
Multi-select grid supports maximum selection size. Demo updated.
> GridMultiSelect done

- demo-v14/src/main/java/org/vaadin/miki/demo/builders/ItemGridBuilder.java
- demo-v14/src/main/java/org/vaadin/miki/demo/providers/ItemGridGenerators.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/CellInformation.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/ItemGrid.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/RowPadding.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/RowPaddingStrategies.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/RowPaddingStrategy.java
- superfields/src/test/java/org/vaadin/miki/superfields/itemgrid/ItemGridTest.java
> ItemGrid item padding done (#250)

- superfields/release-notes.md
Automatically updated notes 0.9.3.
> Release notes for version 0.9.3

- demo-v14/src/main/java/org/vaadin/miki/demo/builders/HasDatePatternBuilder.java
- superfields/src/main/resources/META-INF/resources/frontend/super-date-time-picker.js
closes #260 
closes #87 
those tickets might have been related
> superdatetimepicker type error no longer shown

- superfields/release-notes.md
Automatically updated notes 0.9.4.
> Release notes for version 0.9.4

- superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperDoubleField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperIntegerField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperLongField.java
really, there is not much that can be done about it
> silenced sonar warnings about more than 5 superclasses

- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/SuperBigDecimalField.java
> #268 fixed, hopefully

- .github/workflows/deployheroku.yml
- .github/workflows/maven.yml
- .github/workflows/mavenpublish.yml
- .github/workflows/setversion.yml
- README.md
- pom.xml
The minimum Java version should now be 11.
> #280 minimum Java turned to 11

- superfields/release-notes.md
Automatically updated notes 0.10.0.
> Release notes for version 0.10.0

- demo-v14/src/main/java/org/vaadin/miki/demo/providers/SuperIntegerFieldProvider.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/BaseTestsForIntegerNumbers.java
slightly modified how parsing of input is done with number fields; and added a test to check for regressions of this in the future
closes #284
> #284 fixed

- demo-v14/package-lock.json
- demo-v14/package.json
- demo-v14/webpack.generated.js
- pom.xml
- superfields/pom.xml
> #286 done, Vaadin bumped to 14.5.1

- superfields/release-notes.md
Automatically updated notes 0.10.1.
> Release notes for version 0.10.1

- pom.xml
- superfields/README.md
- superfields/pom.xml
- superfields/src/main/java/org/vaadin/miki/events/state/StateChangeEvent.java
- superfields/src/main/java/org/vaadin/miki/events/state/StateChangeListener.java
- superfields/src/main/java/org/vaadin/miki/superfields/dates/SuperDatePickerI18n.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
> #292 #293 done

- superfields/release-notes.md
Automatically updated notes 0.10.2.
> Release notes for version 0.10.2

- demo-v14/src/main/java/org/vaadin/miki/Bug305Page.java
- demo-v14/src/main/java/org/vaadin/miki/demo/builders/AbstractSuperFloatingPointFieldBuilder.java
- demo-v14/src/main/java/org/vaadin/miki/demo/providers/SuperDoubleFieldProvider.java
- superfields/README.md
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperFloatingPointField.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/BaseTestsForFloatingPointNumbers.java
closes #304 
now possible to `setIntegerPartOptional`
> #304 omit leading zero

- superfields/release-notes.md
Automatically updated notes 0.11.0.
> Release notes for version 0.11.0

- superfields/release-notes.md
Automatically updated notes 0.11.1.
> Release notes for version 0.11.1

- demo-v14/package-lock.json
- demo-v14/src/main/java/org/vaadin/miki/demo/builders/HasClearButtonBuilder.java
- demo-v14/src/main/java/org/vaadin/miki/demo/builders/HasValueChangeModeBuilder.java
- superfields/src/main/java/org/vaadin/miki/markers/HasClearButton.java
- superfields/src/main/java/org/vaadin/miki/markers/WithClearButtonMixin.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
- superfields/src/main/java/org/vaadin/miki/superfields/text/SuperTextArea.java
- superfields/src/main/java/org/vaadin/miki/superfields/text/SuperTextField.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperBigDecimalFieldTest.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperDoubleFieldTest.java
number fields now support value change mode
they also support clear button, which is in its own interface
closes #337
> #337 valuechangemode and clear buttons

- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperBigDecimalFieldTest.java
- superfields/src/test/java/org/vaadin/miki/superfields/numbers/SuperDoubleFieldTest.java
tests show that changing fraction digits is no longer destructive
closes #339
> #339 non-destructive format changes

- README.md
everything else will be updated when a release is made
closes #341
> #341 updated docs

- superfields/release-notes.md
Automatically updated notes 0.11.2.
> Release notes for version 0.11.2

- superfields/release-notes.md
Automatically updated notes 0.12.0.
> Release notes for version 0.12.0

- superfields/release-notes.md
Automatically updated notes 0.13.0.
> Release notes for version 0.13.0

- superfields/pom.xml
> #371 first try

- superfields/src/main/java/org/vaadin/miki/superfields/collections/CollectionField.java
- superfields/src/main/java/org/vaadin/miki/superfields/collections/HasCollectionElementFilter.java
- superfields/src/main/java/org/vaadin/miki/superfields/collections/MapField.java
- superfields/src/main/java/org/vaadin/miki/superfields/collections/WithCollectionElementFilterMixin.java
- superfields/src/main/java/org/vaadin/miki/superfields/layouts/HeaderFooterFieldWrapper.java
- superfields/src/main/java/org/vaadin/miki/superfields/util/CollectionComponentProviders.java
- superfields/src/test/java/org/vaadin/miki/superfields/collections/IntegerNonNullableSetCollectionFieldTest.java
- superfields/src/test/java/org/vaadin/miki/superfields/collections/StringListCollectionFieldTest.java
- superfields/src/test/java/org/vaadin/miki/superfields/collections/StringSetCollectionFieldTest.java
- superfields/src/test/java/org/vaadin/miki/superfields/layouts/HeaderFooterFieldWrapperTest.java
> CollectionField has now element filters

- superfields/release-notes.md
Automatically updated notes 0.13.1.
> Release notes for version 0.13.1

- .gitignore
- demo-v23/frontend/generated/vaadin-featureflags.ts
- demo-v23/frontend/styles/demo-styles.css
- demo-v23/src/main/java/org/vaadin/miki/InfoPage.java
- demo-v23/src/main/java/org/vaadin/miki/demo/providers/CollectionFieldProvider.java
- demo-v23/src/main/java/org/vaadin/miki/demo/providers/ItemGridProvider.java
- demo-v23/src/main/java/org/vaadin/miki/demo/providers/MapFieldProvider.java
- demo-v23/src/main/java/org/vaadin/miki/demo/providers/ObjectFieldProvider.java
- demo-v23/src/main/java/org/vaadin/miki/demo/providers/ObservedFieldProvider.java
- demo-v23/src/main/resources/ObjectField.md
- pom.xml
- superfields/README.md
- superfields/pom.xml
also modified a bit the demo app
closes #390 
closes #391
> #390 #391 Vaadin 23.2 and updated docs

- demo-v23/src/main/java/org/vaadin/miki/demo/providers/MapFieldProvider.java
- superfields/src/main/java/org/vaadin/miki/superfields/collections/MapEntryField.java
- superfields/src/main/java/org/vaadin/miki/superfields/layouts/HeaderFooterFieldWrapper.java
events related to value change are now properly fired from various components
closes #388 
closes #395 
closes #396
> #388 #395 #396 fixed

- superfields/release-notes.md
Automatically updated notes 0.14.0.
> Release notes for version 0.14.0

- superfields/src/main/java/org/vaadin/miki/markers/HasReadOnly.java
- superfields/src/main/java/org/vaadin/miki/superfields/checkbox/SuperCheckbox.java
- superfields/src/main/java/org/vaadin/miki/superfields/layouts/HeaderFooterLayoutWrapper.java
- superfields/src/main/java/org/vaadin/miki/superfields/util/factory/ObjectFieldFactory.java
- superfields/src/test/java/org/vaadin/miki/markers/HasReadOnlyTest.java
- superfields/src/test/java/org/vaadin/miki/superfields/checkbox/SuperCheckboxTest.java
- superfields/src/test/java/org/vaadin/miki/superfields/layouts/HeaderFooterLayoutWrapperTest.java
fixed layout bugs, also layouts do not get disabled themselves (only components they contain)
introduced `SuperCheckbox`
closes #402 
closes #403 
closes #404
> #402 #403 #404 done

- superfields/release-notes.md
Automatically updated notes 0.14.1.
> Release notes for version 0.14.1

- superfields/src/main/java/org/vaadin/miki/superfields/checkbox/SuperCheckbox.java
- superfields/src/test/java/org/vaadin/miki/superfields/checkbox/SuperCheckboxTest.java
> #416 fixed, hopefully

- superfields/release-notes.md
Automatically updated notes 0.15.0.
> Release notes for version 0.15.0

- .github/workflows/publish-central.yml
- .github/workflows/publish-github.yml
- README.md
- demo-v23/pom.xml
- pom.xml
- superfields/pom.xml
- superfields/src/main/java/org/vaadin/miki/superfields/gridselect/AbstractGridSelect.java
- superfields/src/main/java/org/vaadin/miki/superfields/gridselect/GridMultiSelect.java
- superfields/src/main/java/org/vaadin/miki/superfields/object/builder/SimplePropertyComponentBuilder.java
- superfields/src/main/java/org/vaadin/miki/superfields/object/reflect/ReflectivePropertyProvider.java
project is hopefully releasable to Maven Central now
closes #366
> #366 hopefully done

- README.md
> #431 updated docs

- superfields/release-notes.md
Automatically updated notes 0.16.0.
> Release notes for version 0.16.0

- .github/workflows/publish-java8-central.yml
> #443 hopefully done

- superfields/release-notes.md
Automatically updated notes 0.17.0.
> Release notes for version 0.17.0

- superfields/src/main/java/org/vaadin/miki/markers/HasReadOnly.java
- superfields/src/main/java/org/vaadin/miki/markers/WithLabelPositionableMixin.java
- superfields/src/main/java/org/vaadin/miki/markers/WithRequiredMixin.java
- superfields/src/main/java/org/vaadin/miki/superfields/buttons/SimpleButtonState.java
- superfields/src/main/java/org/vaadin/miki/superfields/collections/CollectionField.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/ItemGrid.java
- superfields/src/main/java/org/vaadin/miki/superfields/itemgrid/RowPadding.java
- superfields/src/main/java/org/vaadin/miki/superfields/layouts/HeaderFooterFieldWrapper.java
- superfields/src/main/java/org/vaadin/miki/superfields/object/ObjectField.java
- superfields/src/main/java/org/vaadin/miki/superfields/object/builder/SimplePropertyComponentBuilder.java
- superfields/src/main/java/org/vaadin/miki/superfields/object/reflect/ReflectivePropertyProvider.java
- superfields/src/main/java/org/vaadin/miki/superfields/tabs/SuperTabs.java
- superfields/src/main/java/org/vaadin/miki/superfields/util/factory/ObjectFieldFactory.java
- superfields/src/main/java/org/vaadin/miki/util/ComponentTools.java
- superfields/src/main/java/org/vaadin/miki/util/ReflectTools.java
> #463 using some java 17 features

- superfields/release-notes.md
Automatically updated notes 0.18.0.
> Release notes for version 0.18.0

- .github/workflows/publish-central.yml
- demo-v24/pom.xml
- superfields/pom.xml
- superfields/release-notes.md
> #467 hopefully done

- demo-v24/src/main/java/org/vaadin/miki/demo/builders/AbstractSuperNumberFieldBuilder.java
- demo-v24/src/main/java/org/vaadin/miki/demo/builders/SuperTextFieldBuilder.java
- superfields/README.md
- superfields/src/main/java/org/vaadin/miki/markers/HasInvalidInputPrevention.java
- superfields/src/main/java/org/vaadin/miki/markers/WithInvalidInputPreventionMixin.java
- superfields/src/main/java/org/vaadin/miki/superfields/numbers/AbstractSuperNumberField.java
- superfields/src/main/java/org/vaadin/miki/superfields/text/SuperTextField.java
- superfields/src/main/resources/META-INF/resources/frontend/super-text-field.js
> #473 setPreventingInvalidInput done

- superfields/release-notes.md
Automatically updated notes 0.18.3.
> Release notes for version 0.18.3

- superfields/release-notes.md
Automatically updated notes 0.19.0.
> Release notes for version 0.19.0

- demo-v24/pom.xml
- demo-v24/src/main/java/org/vaadin/miki/InfoPage.java
> #508 likely done

- superfields/src/main/resources/superdatepickeri18n_sv.properties
Adds Swedish translations for superdatepickeri18n.properties as mentioned in issue #54
> Adds Swedish translation to superdatepickeri18n.properties #54

- superfields/release-notes.md
Automatically updated notes 0.19.1.
> Release notes for version 0.19.1

- superfields/release-notes.md
Automatically updated notes 0.19.2.
> Release notes for version 0.19.2

- .github/workflows/codequality.yml
- .github/workflows/deploydemo.yml
- .github/workflows/makerelease.yml
- .github/workflows/maven.yml
- .github/workflows/publish-central.yml
- .github/workflows/publish-github.yml
- .github/workflows/publish-java8-central.yml
- .github/workflows/releasenotes.yml
- .github/workflows/setversion.yml
> #525 likely done

- superfields/release-notes.md
Automatically updated notes 0.19.4.
> Release notes for version 0.19.4

- .github/settings.xml
- superfields/pom.xml
> #543 hopefully done

- superfields/release-notes.md
Automatically updated notes 0.19.5.
> Release notes for version 0.19.5

- demo-v24/pom.xml
> #556 ensured demo app uses core vaadin
